// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1382, height: 754 })
    await driver.findElement(By.css(".Navbar_navbar__logo__LncWD")).click()
    await driver.findElement(By.css(".Product_product__2v-8g:nth-child(1) > .Product_product__buttons__2BRwe > .Product_buttons__btn__3l0mP")).click()
    await driver.findElement(By.css(".Product_product__2v-8g:nth-child(1) a > .Product_buttons__btn__3l0mP")).click()
    await driver.findElement(By.css(".SingleItem_details__addBtn__3RVj3")).click()
    await driver.findElement(By.css(".SingleItem_details__addBtn__3RVj3")).click()
    await driver.findElement(By.css(".SingleItem_details__addBtn__3RVj3")).click()
    await driver.findElement(By.css(".Navbar_cart__image__2qklE")).click()
    {
      const element = await driver.findElement(By.css(".Navbar_cart__image__2qklE"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("qty")).sendKeys("5")
    await driver.findElement(By.id("qty")).click()
    await driver.findElement(By.id("qty")).sendKeys("6")
    await driver.findElement(By.id("qty")).click()
    await driver.findElement(By.id("qty")).sendKeys("7")
    await driver.findElement(By.id("qty")).click()
    await driver.findElement(By.id("qty")).sendKeys("8")
    await driver.findElement(By.id("qty")).click()
    {
      const element = await driver.findElement(By.id("qty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".CartItem_actions__deleteItemBtn__2hZT1 > img")).click()
    await driver.findElement(By.css(".Navbar_navbar__logo__LncWD")).click()
    await driver.findElement(By.css(".Product_product__2v-8g:nth-child(1) a > .Product_buttons__btn__3l0mP")).click()
    await driver.findElement(By.css(".SingleItem_details__addBtn__3RVj3")).click()
    await driver.findElement(By.css(".Navbar_cart__counter__2K_yA")).click()
    {
      const element = await driver.findElement(By.css(".Navbar_cart__counter__2K_yA"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("qty")).sendKeys("2")
    await driver.findElement(By.id("qty")).click()
    await driver.findElement(By.id("qty")).sendKeys("3")
    await driver.findElement(By.id("qty")).click()
    {
      const element = await driver.findElement(By.id("qty"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("qty")).sendKeys("4")
    await driver.findElement(By.id("qty")).click()
    await driver.findElement(By.id("qty")).sendKeys("5")
    await driver.findElement(By.id("qty")).click()
    await driver.findElement(By.id("qty")).sendKeys("6")
    await driver.findElement(By.id("qty")).click()
    await driver.findElement(By.id("qty")).sendKeys("7")
    await driver.findElement(By.id("qty")).click()
    await driver.findElement(By.id("qty")).sendKeys("8")
    await driver.findElement(By.id("qty")).click()
    await driver.findElement(By.css(".Navbar_navbar__logo__LncWD")).click()
    {
      const element = await driver.findElement(By.css(".Navbar_navbar__logo__LncWD"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".Product_product__2v-8g:nth-child(2) > .Product_product__image__3UUmI")).click()
  })
})
